[general]
    database = "app.db"
    interval = "1h"

[matrix]
    home_server = "matrix.org"
    username = "@test:matrix.org"
    access_token = "ckAtHJpY2Vz_lnEqWRKRBgsoqFDKJmAm_10Wwxd"
    room_id = "!Hy13Jfkfirhu:matrix.org"

[[products]]
    name = "Byoma Moisturizing Gel Cream"
    base_price = 11.99

    [products.links]
    boots = "https://www.boots.com/byoma-moisturizing-gel-cream-50ml-10307026"
    amazon = "https://www.amazon.co.uk/BYOMA-Moisturizing-Gel-Cream-50ml/dp/B0BJ74DJXG"

[[products]]
    name = "Byoma Balancing Face Mist"
    base_price = 11.99

    [products.links]
    boots = "https://www.boots.com/byoma-balancing-face-mist-100ml-10307029"
    amazon = "https://www.amazon.co.uk/BYOMA-Balancing-Hydrating-Face-100ml/dp/B0C7C8D9LS"

[[products]]
    name = "INKEY List Oat Cleansing Balm"
    base_price = 12.00

    [products.links]
    boots = "https://www.boots.com/the-inkey-list-oat-cleansing-balm-150ml-10278182"
    amazon = "https://www.amazon.co.uk/INKEY-List-Cleansing-Removes-Sensitive/dp/B09MRD1648"

[[products]]
    name = "INKEY List Q10 Serum"
    base_price = 9.00

    [products.links]
    amazon = "https://www.amazon.co.uk/INKEY-List-Antioxidant-Serum-Protect-dp-B09N9ZKWT8/dp/B09N9ZKWT8"
    lookFantastic = "https://www.lookfantastic.com/p/the-inkey-list-q10-serum-30ml/12208008/"
